tutorial/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('polls/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('polls/<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('polls/<int:question_id>/vote/', views.vote, name='vote'),
    path('polls/new_Question', views.NewQuestionView.as_view(), name='newQuestion'),
    path('polls/new_Choice/', views.NewChoiceView.as_view(), name='newChoice'),
    path('polls/<int:pk>/delete_question', views.DeleteQuestionView.as_view(), name='deleteQuestion'),
    path('polls/<int:pk>/edit_question', views.EditQuestionView.as_view(), name='editQuestion'),
    path('polls/<int:pk>/list_choice', views.DetailChoiceView.as_view(), name='listChoice'),
    path('polls/<int:pk>/delete_choice', views.DeleteChoiceView.as_view(), name='deleteChoice'),
    path('polls/<int:pk>/edit_choice', views.EditChoiceView.as_view(), name='editChoice'),

]

tutorial/tutorial/urls.py
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),

]

tutorial/polls/models.py
from django.db import models
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    order = models.IntegerField(default=1)

    def __str__(self):
        return self.choice_text

tutorial/polls/forms.py
from django import forms

from .models import Question, Choice

from django.forms.models import inlineformset_factory


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question_text',)


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ('question', 'choice_text',)


class TextForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ('choice_text',)

tutorial/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from .models import Choice, Question
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .forms import QuestionForm, ChoiceForm, TextForm

from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    model = Question

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class NewQuestionView(CreateView):
    form_class = QuestionForm
    template_name = 'polls/new_question.html'
    success_url = reverse_lazy('polls:index')
    model = Question

    def form_valid(self, form):
        form.instance.pub_date = timezone.now()
        return super(NewQuestionView, self).form_valid(form)


class NewChoiceView(CreateView):
    form_class = ChoiceForm
    template_name = 'polls/edit_choice.html'
    model = Choice
    success_url = reverse_lazy('polls:index')


class DeleteQuestionView(DeleteView):
    model = Question
    success_url = reverse_lazy('polls:index')


class EditQuestionView(UpdateView):
    form_class = QuestionForm
    template_name = 'polls/new_question.html'
    model = Question
    success_url = reverse_lazy('polls:index')

    def get_context_data(self, **kwargs):
        context = super(EditQuestionView, self).get_context_data(**kwargs)
        context['test'] = 'success'
        return context


class DetailChoiceView(generic.DetailView):
    model = Question
    template_name = 'polls/list_choice.html'


class DeleteChoiceView(DeleteView):
    model = Choice

    def get_success_url(self):
        return reverse_lazy('polls:listChoice', kwargs={'pk': self.object.question.pk})


class EditChoiceView(UpdateView):
    form_class = TextForm
    template_name = 'polls/edit_choice.html'
    model = Choice

    def get_success_url(self):
        return reverse_lazy('polls:listChoice', kwargs={'pk': self.object.question.pk})

tutorial/polls/templates/polls/base.html
{% load static %}

<html>
    <head>
        <title>Questions and choices</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
             {% include 'polls/button.html'%}
             {% include 'polls/buttonchoice.html'%}

            {% endif %}
            <h1><a href="/">Questions and choices</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

tutorial/polls/templates/polls/button.html
<a href="{% url 'polls:newQuestion' %}" class="top-menu btn btn-info" ><span class="glyphicon glyphicon-plus">Add Question</span></a>

tutorial/polls/templates/polls/buttonchoice.html
<a href="{% url 'polls:newChoice' %}" class="top-menu btn btn-info" ><span class="glyphicon glyphicon-plus">Add choice</span></a>

tutorial/polls/templates/polls/buttonchoicedit.html
<a class="btn btn-default" href="{% url 'polls:editChoice' pk=c.pk%}">Edit text</a>

tutorial/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

tutorial/polls/templates/polls/edit_choice.html
{% extends 'polls/base.html' %}

{% block content %}
    {% if new == True%}
    <h1>Add choice</h1>
    {% else %}
     <h1>Edit choice</h1>
    {% endif%}
    {{ form.errors }}
    <form method="POST">{% csrf_token %}
        {{ form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

tutorial/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% load static %}

<link rel="stylesheet" href="{% static 'style.css' %}">

{% block content %}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        <form method="POST" action = "{% url 'polls:deleteQuestion' pk=question.pk %}">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit">delete Question</button>
        </form>

        <a class="btn btn-default" href="{% url 'polls:listChoice' pk=question.pk %}"><span class="glyphicon glyphicon-pencil">choices list</span></a>
        <a class="btn btn-default" href="{% url 'polls:editQuestion' pk=question.pk %}"><span class="glyphicon glyphicon-pencil">Edit question</span></a>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

tutorial/polls/templates/polls/list_choice.html
{% extends 'polls/base.html' %}
{% block content %}

    <h1>{{ question.question_text }}</h1>

    {% for choice in question.choice_set.all %}
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>

        <form action="{% url 'polls:deleteChoice' choice.id %}" method="post">
            <input type="submit" value="delete">
            {% csrf_token %}
        </form>

        {% include 'polls/buttonchoicedit.html'  with c=choice %}
        <br>
    {% endfor %}

{% endblock %}

tutorial/polls/templates/polls/new_question.html
{% extends 'polls/base.html' %}

{% block content %}
 {{ test }}
    {% if object.id%}
    <h1>Edit question</h1>
    {% else %}
    <h1>Add question</h1>
    {%endif%}
    <form method="POST" class="QuestionForm">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

tutorial/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</ul>
<a href="{% url 'polls:index' %}">Choose new question</a>